dev: true

server:
  port: "8080"
  allow_origins:
    - "http://127.0.0.1:3000"

db:
  user_name: "root"
  password: "12345678"
  address: "localhost:3306"
  db_name: "usercenter"

jwt:
  secret: "secretKey"
  issuer: "issuer"
  expires: 48

email:
  sender: "123456@qq.com"
  pwd:  "12345678"
  smtpaddr: "smtp.qq.com"
  smtpport: "465"

